version: '3'
services:
  app:
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=*
      - PYTHONUNBUFFERED=1
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - .:/code
    ports:
      - "8000:8000"
